version: '3.9'

networks:
  database:
    name: database
    driver: bridge
  pickup:
    name: database
    external: true

services:
  pickup:
    image: 'ghcr.io/undercurrent-technologies/pickup:dev'
    container_name: 'pickup'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_USER=${ACCESS_USER}
        - ACCESS_TOKEN=${ACCESS_TOKEN}
    networks:
      - database
      - pickup
    env_file:
      - .env
    ports:
      - 8081:8081
