name: Build Dev Image

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_USER: ${{ secrets.ACCESS_USER }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GOPRIVATE: github.com/Undercurrent-Technologies/kprime-utilities
      IMAGE_TAG: ghcr.io/undercurrent-technologies/pickup:dev
      GIT_TERMINAL_PROMPT: 1
    
    steps:
      - uses: actions/checkout@v3

      - run: git config --global url.https://${ACCESS_USER}:${ACCESS_TOKEN}@github.com/.insteadOf https://github.com

      - name: Build App Image
        run: |
          go mod tidy
          docker build -t ${IMAGE_TAG} .

      - name: Push image to registry
        run: |
          echo ${ACCESS_TOKEN} | docker login ghcr.io -u USERNAME --password-stdin
          
          docker push ${IMAGE_TAG}
